### ISSUE TITLE
type object 'PPODecorators' has no attribute 'empty_cuda_cache'. Did you mean: 'empty_device_cache'?

### ISSUE THREAD

**Issue by hsb1995** [Ledzy/BAdam#4] opened 2024-04-27 09:29 UTC
I will reproduce your code:
Python src/train_bash.py
I used the command you provided: When this situation occurred, I thought it was a module error in Transformers (4.40).
So I dropped to 4.37
![image](https://github.com/Ledzy/BAdam/assets/149936473/f731c0af-7d98-4393-ae3b-e1a4bbfab83e)

**Comment by hsb1995** [comment] 2024-04-27 09:35
![image](https://github.com/Ledzy/BAdam/assets/149936473/fc1bc79f-fdf9-44cb-8048-480631700d10)
And I couldn't find the run_exp code in the code from llmtuner import.
The "ctrl" button also cannot jump over.

**Comment by hsb1995** [comment] 2024-04-27 10:16
I solved it:
use trl==0.7.2

But this problem is:
![image](https://github.com/Ledzy/BAdam/assets/149936473/91301c7c-e41b-49e1-a103-6be7b476307b)
this argument is your provide

**Comment by xiao-li-hub** [comment] 2024-04-27 13:04
For the argument error, please delete "--cutoff_len 1024". We have updated the command sample.

**Comment by hsb1995** [comment] 2024-04-28 13:25
@xiao-li-hub 
Another issue with reproducing code:
![image](https://github.com/Ledzy/BAdam/assets/149936473/46b3b56d-f690-49e3-9efb-4f2e7840c52f)

**Comment by Ledzy** [comment] 2024-04-28 14:03
This error seems to be caused by using multiple GPUs. The current code only supports single GPU training, as mentioned in "readme". The distributed training version is still under development and will be released later.

**Comment by hsb1995** [comment] 2024-04-28 14:05
Yes, professor, but the command you provided has the following parameters. Does this also need to be deleted?
 --per_device_train_batch_size 2 \
 --per_device_eval_batch_size 2 \

**Comment by Ledzy** [comment] 2024-04-28 14:08
No. When using single GPU, `per_device_train_batch_size` means the batch size for training.

**Comment by hsb1995** [comment] 2024-04-28 14:16
> No. When using single GPU, `per_device_train_batch_size` means the batch size for training.

Professor, I originally had two 3090 cards. I default to running according to the parameters you provided. I don't have any parallel behavior or commands on my end. Could you please advise on how to modify this?

**Comment by Ledzy** [comment] 2024-04-28 14:28
You may use exactly the same command as provided in the "readme". It trains the llama 2-7b model using single RTX-3090 (the card 0):

```python
CUDA_VISIBLE_DEVICES=0 python src/train_bash.py \
    --stage sft \
    --model_name_or_path meta-llama/Llama-2-7b \
    --do_train \
    --dataset alpaca_gpt4_en \
    --template default \
    --finetuning_type block \
    --output_dir ./outputs/tmp \
    --overwrite_cache \
    --per_device_train_batch_size 2 \
    --per_device_eval_batch_size 2 \
    --gradient_accumulation_steps 8 \
    --lr_scheduler_type cosine \
    --logging_steps 1 \
    --save_steps 1000 \
    --val_size 500 \
    --eval_steps 20 \
    --evaluation_strategy steps \
    --learning_rate 1e-6 \
    --num_train_epochs 3 \
    --overwrite_output_dir \
    --plot_loss \
    --switch_block_every 100 \
    --switch_mode random \
    --bf16
```

**Comment by hsb1995** [comment] 2024-04-28 14:41
CUDA_VISIBLE_DEVICES=0 python src/train_bash.py \
    --stage sft \
    --model_name_or_path /home/sam/Doctorproject/weight/llama-3-8b/LLM-Research/Llama-3-8b/ \
    --do_train \
    --dataset alpaca_gpt4_en \
    --template default \
    --finetuning_type block \
    --output_dir ./outputs/tmp \
    --overwrite_cache \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 1 \
    --gradient_accumulation_steps 4 \
    --lr_scheduler_type cosine \
    --logging_steps 1 \
    --save_steps 1000 \
    --val_size 500 \
    --eval_steps 20 \
    --evaluation_strategy steps \
    --learning_rate 1e-6 \
    --num_train_epochs 3 \
    --overwrite_output_dir \
    --plot_loss \
    --switch_block_every 100 \
    --switch_mode random \
    --bf16

torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 1.96 GiB. GPU 
  0%|          | 0/38625 [00:02<?, ?it/s]

**Comment by Ledzy** [comment] 2024-04-29 04:04
Hi @hsb1995 , please pull the latest code where we have updated the "llama-alpaca/src/llmtuner/tuner/sft/block_optim.py" used for training llama 3-8b. It should work correctly for 3090.

**Closed as completed** 2024-05-20 08:35 UTC
Labels: solved
